### ISSUE TITLE
Max playlist size is 100 tracks?

### ISSUE THREAD

**Issue by espg** [weskerfoot/Spotify-MPD-Sync#7]
Copied all of my liked songs to a new playlist (since like songs isn't sync'ed)... grabbed the most recent 100 tracks, but left the remaining 450 tracks...

Known issue?

**Comment by weskerfoot** [comment]
> Copied all of my liked songs to a new playlist (since like songs isn't sync'ed)... grabbed the most recent 100 tracks, but left the remaining 450 tracks...
> 
> Known issue?

I haven't run it in a while so maybe something changed on the API side. I'll investigate.

**Comment by weskerfoot** [comment]
You're right, it does seem to limit to 100 tracks by default.

**Comment by weskerfoot** [comment]
Looks like the latest spotify-mpd plugin will properly sync everything anyway, so I would suggest updating to that. It seems to work for me.
